[package]
name = "aaa_project_aaa"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.57.*"

[dependencies]
flutter_rust_bridge = "1.57.*"
